<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Before-your-start:" data-toc-modified-id="Before-your-start:-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Before your start:</a></span></li><li><span><a href="#Introduction" data-toc-modified-id="Introduction-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Introduction</a></span></li><li><span><a href="#Challenge-1---Loading-and-Extracting-Features-from-the-First-Dataset" data-toc-modified-id="Challenge-1---Loading-and-Extracting-Features-from-the-First-Dataset-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Challenge 1 - Loading and Extracting Features from the First Dataset</a></span><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#In-this-challenge,-our-goals-are:" data-toc-modified-id="In-this-challenge,-our-goals-are:-3.0.0.1"><span class="toc-item-num">3.0.0.1&nbsp;&nbsp;</span>In this challenge, our goals are:</a></span></li><li><span><a href="#The-first-dataset-contains-different-information-describing-the-apps." data-toc-modified-id="The-first-dataset-contains-different-information-describing-the-apps.-3.0.0.2"><span class="toc-item-num">3.0.0.2&nbsp;&nbsp;</span>The first dataset contains different information describing the apps.</a></span></li><li><span><a href="#Examine-all-variables-and-their-types-in-the-following-cell" data-toc-modified-id="Examine-all-variables-and-their-types-in-the-following-cell-3.0.0.3"><span class="toc-item-num">3.0.0.3&nbsp;&nbsp;</span>Examine all variables and their types in the following cell</a></span></li><li><span><a href="#Since-this-dataset-only-contains-one-numeric-column,-let's-skip-the-describe()-function-and-look-at-the-first-5-rows-using-the-head()-function" data-toc-modified-id="Since-this-dataset-only-contains-one-numeric-column,-let's-skip-the-describe()-function-and-look-at-the-first-5-rows-using-the-head()-function-3.0.0.4"><span class="toc-item-num">3.0.0.4&nbsp;&nbsp;</span>Since this dataset only contains one numeric column, let's skip the <code>describe()</code> function and look at the first 5 rows using the <code>head()</code> function</a></span></li><li><span><a href="#We-can-see-that-there-are-a-few-columns-that-could-be-coerced-to-numeric." data-toc-modified-id="We-can-see-that-there-are-a-few-columns-that-could-be-coerced-to-numeric.-3.0.0.5"><span class="toc-item-num">3.0.0.5&nbsp;&nbsp;</span>We can see that there are a few columns that could be coerced to numeric.</a></span></li><li><span><a href="#We-see-that-Google-Play-is-using-a-shorthand-for-millions." data-toc-modified-id="We-see-that-Google-Play-is-using-a-shorthand-for-millions.-3.0.0.6"><span class="toc-item-num">3.0.0.6&nbsp;&nbsp;</span>We see that Google Play is using a shorthand for millions.</a></span></li><li><span><a href="#The-next-column-we-will-look-at-is-Size.-We-start-by-looking-at-all-unique-values-in-Size:" data-toc-modified-id="The-next-column-we-will-look-at-is-Size.-We-start-by-looking-at-all-unique-values-in-Size:-3.0.0.7"><span class="toc-item-num">3.0.0.7&nbsp;&nbsp;</span>The next column we will look at is <code>Size</code>. We start by looking at all unique values in <code>Size</code>:</a></span></li><li><span><a href="#While-we-can-convert-most-of-the-Size-values-to-numeric-in-the-same-way-we-converted-the-Reviews-values,-there-is-one-value-that-is-impossible-to-convert." data-toc-modified-id="While-we-can-convert-most-of-the-Size-values-to-numeric-in-the-same-way-we-converted-the-Reviews-values,-there-is-one-value-that-is-impossible-to-convert.-3.0.0.8"><span class="toc-item-num">3.0.0.8&nbsp;&nbsp;</span>While we can convert most of the <code>Size</code> values to numeric in the same way we converted the <code>Reviews</code> values, there is one value that is impossible to convert.</a></span></li><li><span><a href="#While-this-column-may-be-useful-for-other-types-of-analysis,-we-opt-to-drop-it-from-our-dataset." data-toc-modified-id="While-this-column-may-be-useful-for-other-types-of-analysis,-we-opt-to-drop-it-from-our-dataset.-3.0.0.9"><span class="toc-item-num">3.0.0.9&nbsp;&nbsp;</span>While this column may be useful for other types of analysis, we opt to drop it from our dataset.</a></span></li><li><span><a href="#Now-let's-look-at-how-many-missing-values-are-in-each-column." data-toc-modified-id="Now-let's-look-at-how-many-missing-values-are-in-each-column.-3.0.0.10"><span class="toc-item-num">3.0.0.10&nbsp;&nbsp;</span>Now let's look at how many missing values are in each column.</a></span></li><li><span><a href="#What-is-the-proportion-of-the-missing-values-in-Rating-to-the-total-number-of-records?" data-toc-modified-id="What-is-the-proportion-of-the-missing-values-in-Rating-to-the-total-number-of-records?-3.0.0.11"><span class="toc-item-num">3.0.0.11&nbsp;&nbsp;</span>What is the proportion of the missing values in <code>Rating</code> to the total number of records?</a></span></li><li><span><a href="#We-opt-to-preserve-these-columns-and-remove-the-rows-containing-missing-data." data-toc-modified-id="We-opt-to-preserve-these-columns-and-remove-the-rows-containing-missing-data.-3.0.0.12"><span class="toc-item-num">3.0.0.12&nbsp;&nbsp;</span>We opt to preserve these columns and remove the rows containing missing data.</a></span></li><li><span><a href="#Next,-we-look-at-the-Last-Updated-column." data-toc-modified-id="Next,-we-look-at-the-Last-Updated-column.-3.0.0.13"><span class="toc-item-num">3.0.0.13&nbsp;&nbsp;</span>Next, we look at the <code>Last Updated</code> column.</a></span></li><li><span><a href="#The-last-column-we-will-transform-is-Price." data-toc-modified-id="The-last-column-we-will-transform-is-Price.-3.0.0.14"><span class="toc-item-num">3.0.0.14&nbsp;&nbsp;</span>The last column we will transform is <code>Price</code>.</a></span></li><li><span><a href="#First-we-remove-the-dollar-sign.-Do-this-in-the-next-cell-by-applying-the-str.replace-function-to-the-column-to-replace-$-with-an-empty-string-('')." data-toc-modified-id="First-we-remove-the-dollar-sign.-Do-this-in-the-next-cell-by-applying-the-str.replace-function-to-the-column-to-replace-$-with-an-empty-string-('').-3.0.0.15"><span class="toc-item-num">3.0.0.15&nbsp;&nbsp;</span>First we remove the dollar sign. Do this in the next cell by applying the <code>str.replace</code> function to the column to replace <code>$</code> with an empty string (<code>''</code>).</a></span></li><li><span><a href="#Second-step,-coerce-the-Price-Numerical-column-to-numeric." data-toc-modified-id="Second-step,-coerce-the-Price-Numerical-column-to-numeric.-3.0.0.16"><span class="toc-item-num">3.0.0.16&nbsp;&nbsp;</span>Second step, coerce the <code>Price Numerical</code> column to numeric.</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Challenge-2---Loading-and-Extracting-Features-from-the-Second-Dataset" data-toc-modified-id="Challenge-2---Loading-and-Extracting-Features-from-the-Second-Dataset-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Challenge 2 - Loading and Extracting Features from the Second Dataset</a></span><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#This-dataset-contains-the-top-100-reviews-for-each-app." data-toc-modified-id="This-dataset-contains-the-top-100-reviews-for-each-app.-4.0.0.1"><span class="toc-item-num">4.0.0.1&nbsp;&nbsp;</span>This dataset contains the top 100 reviews for each app.</a></span></li><li><span><a href="#The-main-piece-of-information-we-would-like-to-extract-from-this-dataset-is-the-proportion-of-positive-reviews-of-each-app." data-toc-modified-id="The-main-piece-of-information-we-would-like-to-extract-from-this-dataset-is-the-proportion-of-positive-reviews-of-each-app.-4.0.0.2"><span class="toc-item-num">4.0.0.2&nbsp;&nbsp;</span>The main piece of information we would like to extract from this dataset is the proportion of positive reviews of each app.</a></span></li><li><span><a href="#Our-first-step-will-be-to-remove-all-rows-with-missing-sentiment." data-toc-modified-id="Our-first-step-will-be-to-remove-all-rows-with-missing-sentiment.-4.0.0.3"><span class="toc-item-num">4.0.0.3&nbsp;&nbsp;</span>Our first step will be to remove all rows with missing sentiment.</a></span></li><li><span><a href="#Now,-use-the-value_counts()-function-(documentation)-to-get-a-sense-on-how-many-apps-are-in-this-dataset-and-their-review-counts." data-toc-modified-id="Now,-use-the-value_counts()-function-(documentation)-to-get-a-sense-on-how-many-apps-are-in-this-dataset-and-their-review-counts.-4.0.0.4"><span class="toc-item-num">4.0.0.4&nbsp;&nbsp;</span>Now, use the <code>value_counts()</code> function (<a href="https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html" target="_blank">documentation</a>) to get a sense on how many apps are in this dataset and their review counts.</a></span></li><li><span><a href="#Now-the-tough-part-comes.-Let's-plan-how-we-will-achieve-our-goal:" data-toc-modified-id="Now-the-tough-part-comes.-Let's-plan-how-we-will-achieve-our-goal:-4.0.0.5"><span class="toc-item-num">4.0.0.5&nbsp;&nbsp;</span>Now the tough part comes. Let's plan how we will achieve our goal:</a></span></li><li><span><a href="#Step-1:-Count-the-number-of-positive-reviews." data-toc-modified-id="Step-1:-Count-the-number-of-positive-reviews.-4.0.0.6"><span class="toc-item-num">4.0.0.6&nbsp;&nbsp;</span>Step 1: Count the number of positive reviews.</a></span></li><li><span><a href="#Step-2:-Create-a-new-dataframe-to-contain-the-App-name,-the-number-of-positive-reviews,-and-the-total-number-of-reviews-of-each-app" data-toc-modified-id="Step-2:-Create-a-new-dataframe-to-contain-the-App-name,-the-number-of-positive-reviews,-and-the-total-number-of-reviews-of-each-app-4.0.0.7"><span class="toc-item-num">4.0.0.7&nbsp;&nbsp;</span>Step 2: Create a new dataframe to contain the <code>App</code> name, the number of positive reviews, and the total number of reviews of each app</a></span></li><li><span><a href="#Bonus:" data-toc-modified-id="Bonus:-4.0.0.8"><span class="toc-item-num">4.0.0.8&nbsp;&nbsp;</span>Bonus:</a></span></li><li><span><a href="#Add-a-derived-column-to-google_agg-that-is-the-ratio-of-the-Positive-and-the-Total-columns.-Call-this-column-Positive-Ratio." data-toc-modified-id="Add-a-derived-column-to-google_agg-that-is-the-ratio-of-the-Positive-and-the-Total-columns.-Call-this-column-Positive-Ratio.-4.0.0.9"><span class="toc-item-num">4.0.0.9&nbsp;&nbsp;</span>Add a derived column to <code>google_agg</code> that is the ratio of the <code>Positive</code> and the <code>Total</code> columns. Call this column <code>Positive Ratio</code>.</a></span></li><li><span><a href="#Now-drop-the-Positive-and-Total-columns.-Do-this-with-inplace=True." data-toc-modified-id="Now-drop-the-Positive-and-Total-columns.-Do-this-with-inplace=True.-4.0.0.10"><span class="toc-item-num">4.0.0.10&nbsp;&nbsp;</span>Now drop the <code>Positive</code> and <code>Total</code> columns. Do this with <code>inplace=True</code>.</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Challenge-3---Join-the-Dataframes" data-toc-modified-id="Challenge-3---Join-the-Dataframes-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Challenge 3 - Join the Dataframes</a></span><ul class="toc-item"><li><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Let's-look-at-the-final-result-using-the-head()-function.-Your-final-product-should-look-like:" data-toc-modified-id="Let's-look-at-the-final-result-using-the-head()-function.-Your-final-product-should-look-like:-5.0.0.1"><span class="toc-item-num">5.0.0.1&nbsp;&nbsp;</span>Let's look at the final result using the <code>head()</code> function. Your final product should look like:</a></span></li></ul></li></ul></li></ul></li></ul></div>

# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [1]:
#Import your libraries
import numpy as np
import pandas as pd

# Introduction

In this lab, we will use two datasets. Both datasets contain variables that describe apps from the Google Play Store. We will use our knowledge in feature extraction to process these datasets and prepare them for the use of a ML algorithm.

# Challenge 1 - Loading and Extracting Features from the First Dataset

#### In this challenge, our goals are: 

* Exploring the dataset.
* Identify the columns with missing values.
* Either replacing the missing values in each column or drop the columns.
* Conver each column to the appropriate type.

#### The first dataset contains different information describing the apps. 

Load the dataset into the variable `google_play` in the cell below. The dataset is in the file `googleplaystore.csv`

In [2]:
google_play=pd.read_csv(r'C:\Users\Arthur\248_Repo\Labs\module_3\Feature-Extraction\data\googleplaystore.csv')

#### Examine all variables and their types in the following cell

In [3]:
google_play.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

#### Since this dataset only contains one numeric column, let's skip the `describe()` function and look at the first 5 rows using the `head()` function

In [4]:
google_play.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [5]:
google_play.sample(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
5747,AW Training,FAMILY,4.6,11,17M,"1,000+",Free,0,Everyone,Education,"July 5, 2018",3.3.2,4.0.3 and up
342,Viber Messenger,COMMUNICATION,4.3,11334799,Varies with device,"500,000,000+",Free,0,Everyone,Communication,"July 18, 2018",Varies with device,Varies with device
8827,DS Barometer - Altimeter and Weather Information,WEATHER,3.9,2962,4.2M,"100,000+",Free,0,Everyone,Weather,"July 9, 2018",3.67,2.3.3 and up
2064,Papumba Academy - Fun Learning For Kids,FAMILY,4.4,496,94M,"100,000+",Free,0,Everyone,Education;Education,"July 11, 2018",1.0,4.2 and up
481,AMBW Dating App: Asian Men Black Women Interra...,DATING,3.5,2,17M,100+,Paid,$7.99,Mature 17+,Dating,"January 21, 2017",1.0.1,4.0 and up

#### We can see that there are a few columns that could be coerced to numeric.

Start with the reviews column. We can evaluate what value is causing this column to be of object type finding the non-numeric values in this column. To do this, we recall the `to_numeric()` function. With this function, we are able to coerce all non-numeric data to null. We can then use the `isnull()` function to subset our dataframe using the True/False column that this function generates.

In the cell below, transform the Reviews column to numeric and assign this new column to the variable `Reviews_numeric`. Make sure to coerce the errors.

In [6]:
google_play['Reviews_numeric'] = pd.to_numeric(google_play['Reviews'], errors='coerce')

Next, create a column containing True/False values using the `isnull()` function. Assign this column to the `Reviews_isnull` variable.

In [7]:
google_play['Reviews_numeric'].isnull().sum()

1

In [8]:
google_play['Reviews_isnull']=google_play['Reviews_numeric'].isnull()
google_play

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159.0,False
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967.0,False
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510.0,False
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,215644.0,False
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,967.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,38.0,False
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,4.0,False
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,3.0,False
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,114.0,False
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,398307.0,False

Finally, subset the `google_play` with `Reviews_isnull`. This should give you all the rows that contain non-numeric characters.

Your output should look like:

![Reviews_bool.png](../images/reviews-bool.png)

In [9]:
google_play.loc[google_play['Reviews_isnull']==True]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,True

#### We see that Google Play is using a shorthand for millions. 

Let's write a function to transform this data.

Steps:

1. Create a function that returns the correct numeric values of *Reviews*.
1. Define a test string with `M` in the last character.
1. Test your function with the test string. Make sure your function works correctly. If not, modify your functions and test again.

In [10]:
# Your code here

def convert_string_to_numeric(s):
    """
    Convert a string value to numeric. If the last character of the string is `M`, obtain the 
    numeric part of the string, multiply it with 1,000,000, then return the result. Otherwise, 
    convert the string to numeric value and return the result.
    
    Args:
        s: The Reviews score in string format.

    Returns:
        The correct numeric value of the Reviews score.
    """
    if s[-1] == 'M':
        v = s.replace('M','')
        w = pd.to_numeric(v)        
        z = w*1000000
        return z
    else:
        a = pd.to_numeric(s)
        return a

In [11]:
test_string = '4.0M'

In [12]:
type(convert_string_to_numeric(test_string))

numpy.float64

The last step is to apply the function to the `Reviews` column in the following cell:

In [13]:
google_play['Reviews']=google_play['Reviews'].map(convert_string_to_numeric)

Check the non-numeric `Reviews` row again. It should have been fixed now and you should see:

![Reviews_bool_fixed.png](../images/reviews-bool-fixed.png)

In [14]:
google_play.loc[google_play['Reviews_isnull']==True]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3000000.0,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN,NaN,True

Also check the variable types of `google_play`. The `Reviews` column should be a `float64` type now.

In [15]:
google_play.dtypes

App                 object
Category            object
Rating             float64
Reviews            float64
Size                object
Installs            object
Type                object
Price               object
Content Rating      object
Genres              object
Last Updated        object
Current Ver         object
Android Ver         object
Reviews_numeric    float64
Reviews_isnull        bool
dtype: object

#### The next column we will look at is `Size`. We start by looking at all unique values in `Size`:

*Hint: use `unique()` ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.unique.html))*.

In [16]:
google_play.Size.unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '1,000+',
       '470k', '226k', '240k', '89k', '234k', '257k', '861k', '467k',
       '157k', '44k', '676k', '67k', '552k', '885k', '1020k', '582k',
       '619k'], dtype=object)

You should have seen lots of unique values of the app sizes.

#### While we can convert most of the `Size` values to numeric in the same way we converted the `Reviews` values, there is one value that is impossible to convert.

What is that badass value? Enter it in the next cell and calculate the proportion of its occurence to the total number of records of `google_play`.

In [17]:
(google_play.Size == 'Varies with device').sum()/len(google_play.Size)

0.15635089013928605

#### While this column may be useful for other types of analysis, we opt to drop it from our dataset. 

There are two reasons. First, the majority of the data are ordinal but a sizeable proportion are missing because we cannot convert them to numerical values. Ordinal data are both numerical and categorical, and they usually can be ranked (e.g. 82k is smaller than 91M). In contrast, non-ordinal categorical data such as blood type and eye color cannot be ranked. The second reason is as a categorical column, it has too many unique values to produce meaningful insights. Therefore, in our case the simplest strategy would be to drop the column.

Drop the column in the cell below (use `inplace=True`)

In [18]:
google_play.drop(['Size'], axis=1, inplace=True)
google_play

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,159.0,False
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,967.0,False
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,87510.0,False
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,215644.0,False
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,967.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38.0,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,38.0,False
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4.0,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,4.0,False
10838,Parkinson Exercices FR,MEDICAL,NaN,3.0,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,3.0,False
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114.0,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,114.0,False
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307.0,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,398307.0,False

#### Now let's look at how many missing values are in each column. 

This will give us an idea of whether we should come up with a missing data strategy or give up on the column all together. In the next column, find the number of missing values in each column: 

*Hint: use the `isna()` and `sum()` functions.*

In [19]:
google_play.isna().sum()

App                   0
Category              0
Rating             1474
Reviews               0
Installs              0
Type                  1
Price                 0
Content Rating        1
Genres                0
Last Updated          0
Current Ver           8
Android Ver           3
Reviews_numeric       1
Reviews_isnull        0
dtype: int64

You should find the column with the most missing values is now `Rating`.

#### What is the proportion of the missing values in `Rating` to the total number of records?

Enter your answer in the cell below.

In [20]:
google_play['Rating'].isna().sum()/len(google_play['Rating'])

0.13596531685268887

A sizeable proportion of the `Rating` column is missing. A few other columns also contain several missing values.

#### We opt to preserve these columns and remove the rows containing missing data.

In particular, we don't want to drop the `Rating` column because:

* It is one of the most important columns in our dataset. 

* Since the dataset is not a time series, the loss of these rows will not have a negative impact on our ability to analyze the data. It will, however, cause us to lose some meaningful observations. But the loss is limited compared to the gain we receive by preserving these columns.

In the cell below, remove all rows containing at least one missing value. Use the `dropna()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.dropna.html)). Assign the new dataframe to the variable `google_missing_removed`.

In [21]:
google_play.info()
google_play.loc[google_play['Rating'].isna()]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   App              10841 non-null  object
 1   Category         10841 non-null  object
 2   Rating           9367 non-null   float64
 3   Reviews          10841 non-null  float64
 4   Installs         10841 non-null  object
 5   Type             10840 non-null  object
 6   Price            10841 non-null  object
 7   Content Rating   10840 non-null  object
 8   Genres           10841 non-null  object
 9   Last Updated     10841 non-null  object
 10  Current Ver      10833 non-null  object
 11  Android Ver      10838 non-null  object
 12  Reviews_numeric  10840 non-null  float64
 13  Reviews_isnull   10841 non-null  bool
dtypes: bool(1), float64(3), object(10)
memory usage: 1.1+ MB

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
23,Mcqueen Coloring pages,ART_AND_DESIGN,NaN,61.0,"100,000+",Free,0,Everyone,Art & Design;Action & Adventure,"March 7, 2018",1.0.0,4.1 and up,61.0,False
113,Wrinkles and rejuvenation,BEAUTY,NaN,182.0,"100,000+",Free,0,Everyone 10+,Beauty,"September 20, 2017",8.0,3.0 and up,182.0,False
123,Manicure - nail design,BEAUTY,NaN,119.0,"50,000+",Free,0,Everyone,Beauty,"July 23, 2018",1.3,4.1 and up,119.0,False
126,Skin Care and Natural Beauty,BEAUTY,NaN,654.0,"100,000+",Free,0,Teen,Beauty,"July 17, 2018",1.15,4.1 and up,654.0,False
129,"Secrets of beauty, youth and health",BEAUTY,NaN,77.0,"10,000+",Free,0,Mature 17+,Beauty,"August 8, 2017",2.0,2.3 and up,77.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10824,Cardio-FR,MEDICAL,NaN,67.0,"10,000+",Free,0,Everyone,Medical,"July 31, 2018",2.2.2,4.4 and up,67.0,False
10825,Naruto & Boruto FR,SOCIAL,NaN,7.0,100+,Free,0,Teen,Social,"February 2, 2018",1.0,4.0 and up,7.0,False
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38.0,"5,000+",Free,0,Everyone,Maps & Navigation,"June 13, 2018",2.0.148.0,4.0 and up,38.0,False
10835,FR Forms,BUSINESS,NaN,0.0,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up,0.0,False
10838,Parkinson Exercices FR,MEDICAL,NaN,3.0,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,3.0,False

In [22]:
google_missing_removed = google_play.dropna()
google_missing_removed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9360 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   App              9360 non-null   object
 1   Category         9360 non-null   object
 2   Rating           9360 non-null   float64
 3   Reviews          9360 non-null   float64
 4   Installs         9360 non-null   object
 5   Type             9360 non-null   object
 6   Price            9360 non-null   object
 7   Content Rating   9360 non-null   object
 8   Genres           9360 non-null   object
 9   Last Updated     9360 non-null   object
 10  Current Ver      9360 non-null   object
 11  Android Ver      9360 non-null   object
 12  Reviews_numeric  9360 non-null   float64
 13  Reviews_isnull   9360 non-null   bool
dtypes: bool(1), float64(3), object(10)
memory usage: 1.0+ MB

From now on, we use the `google_missing_removed` variable instead of `google_play`.

#### Next, we look at the `Last Updated` column.

The `Last Updated` column seems to contain a date, though it is classified as an object type. Let's convert this column using the `pd.to_datetime` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.to_datetime.html)).

In [23]:
google_missing_removed['Last Updated'] = pd.to_datetime(google_missing_removed['Last Updated'])
google_missing_removed.head()

<ipython-input-23-4614d560e412>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  google_missing_removed['Last Updated'] = pd.to_datetime(google_missing_removed['Last Updated'])

,App,Category,Rating,Reviews,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Reviews_numeric,Reviews_isnull
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,"10,000+",Free,0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,159.0,False
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,967.0,False
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,"5,000,000+",Free,0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,87510.0,False
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,"50,000,000+",Free,0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,215644.0,False
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,"100,000+",Free,0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,967.0,False

#### The last column we will transform is `Price`. 

We start by looking at the unique values of this column.

In [24]:
google_missing_removed['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$7.99', '$5.99', '$2.99', '$3.49',
       '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49', '$10.00',
       '$24.99', '$11.99', '$79.99', '$16.99', '$14.99', '$29.99',
       '$12.99', '$2.49', '$10.99', '$1.50', '$19.99', '$15.99', '$33.99',
       '$39.99', '$3.95', '$4.49', '$1.70', '$8.99', '$1.49', '$3.88',
       '$399.99', '$17.99', '$400.00', '$3.02', '$1.76', '$4.84', '$4.77',
       '$1.61', '$2.50', '$1.59', '$6.49', '$1.29', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$8.49', '$1.75', '$14.00', '$2.00',
       '$3.08', '$2.59', '$19.40', '$3.90', '$4.59', '$15.46', '$3.04',
       '$13.99', '$4.29', '$3.28', '$4.60', '$1.00', '$2.95', '$2.90',
       '$1.97', '$2.56', '$1.20'], dtype=object)

Since all prices are ordinal data without exceptions, we can tranform this column by removing the dollar sign and converting to numeric. We can create a new column called `Price Numerical` and drop the original column.

We will achieve our goal in three steps. Follow the instructions of each step below.

#### First we remove the dollar sign. Do this in the next cell by applying the `str.replace` function to the column to replace `$` with an empty string (`''`).

In [25]:
google_missing_removed['Price Numerical']=google_missing_removed['Price'].str.replace('$','')
google_missing_removed['Price Numerical'].sample(5)

<ipython-input-25-e3044538bc2b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  google_missing_removed['Price Numerical']=google_missing_removed['Price'].str.replace('$','')

4778    0
1231    0
4907    0
9395    0
4445    0
Name: Price Numerical, dtype: object

#### Second step, coerce the `Price Numerical` column to numeric.

In [26]:
google_missing_removed['Price Numerical'] = pd.to_numeric(google_missing_removed['Price Numerical'])
google_missing_removed['Price Numerical']

<ipython-input-26-c77770c1e085>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  google_missing_removed['Price Numerical'] = pd.to_numeric(google_missing_removed['Price Numerical'])

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
10834    0.0
10836    0.0
10837    0.0
10839    0.0
10840    0.0
Name: Price Numerical, Length: 9360, dtype: float64

**Finally, drop the original `Price` column.**

In [27]:
google_missing_removed.drop(['Price'], axis=1, inplace=True)

C:\Users\Arthur\anaconda3\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Now check the variable types of `google_missing_removed`. Make sure:

* `Size` and `Price` columns have been removed.
* `Rating`, `Reviews`, and `Price Numerical` have the type of `float64`.
* `Last Updated` has the type of `datetime64`.

In [28]:
google_missing_removed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9360 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   App              9360 non-null   object
 1   Category         9360 non-null   object
 2   Rating           9360 non-null   float64
 3   Reviews          9360 non-null   float64
 4   Installs         9360 non-null   object
 5   Type             9360 non-null   object
 6   Content Rating   9360 non-null   object
 7   Genres           9360 non-null   object
 8   Last Updated     9360 non-null   datetime64[ns]
 9   Current Ver      9360 non-null   object
 10  Android Ver      9360 non-null   object
 11  Reviews_numeric  9360 non-null   float64
 12  Reviews_isnull   9360 non-null   bool
 13  Price Numerical  9360 non-null   float64
dtypes: bool(1), datetime64[ns](1), float64(4), object(8)
memory usage: 1.0+ MB

# Challenge 2 - Loading and Extracting Features from the Second Dataset

Load the second dataset to the variable `google_reviews`. The data is in the file `googleplaystore_user_reviews.csv`.

In [29]:
google_reviews = pd.read_csv(r'C:\Users\Arthur\248_Repo\Labs\module_3\Feature-Extraction\data\googleplaystore_user_reviews.csv')

#### This dataset contains the top 100 reviews for each app. 

Let's examine this dataset using the `head` function

In [30]:
google_reviews.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

#### The main piece of information we would like to extract from this dataset is the proportion of positive reviews of each app. 

Columns like `Sentiment_Polarity` and `Sentiment_Subjectivity` are not to our interests because we have no clue how to use them. We do not care about `Translated_Review` because natural language processing is too complex for us at present (in fact the `Sentiment`, `Sentiment_Polarity`, and `Sentiment_Subjectivity` columns are derived from `Translated_Review` the data scientists). 

What we care about in this challenge is `Sentiment`. To be more precise, we care about **what is the proportion of *Positive* sentiment of each app**. This will require us to aggregate the `Sentiment` data by `App` in order to calculate the proportions.

Now that you are clear about what we are trying to achieve, follow the steps below that will walk you through towards our goal.

#### Our first step will be to remove all rows with missing sentiment. 

In the next cell, drop all rows with missing data using the `dropna()` function and assign this new dataframe to `review_missing_removed`.

In [31]:
review_missing_removed = google_reviews.dropna(subset=['Sentiment'], how='all')
review_missing_removed

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.000000,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.250000,0.288462
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.400000,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.000000,0.300000
5,10 Best Foods for You,Best way,Positive,1.000000,0.300000
...,...,...,...,...,...
64222,Housing-Real Estate & Property,Most ads older many agents ..not much owner po...,Positive,0.173333,0.486667
64223,Housing-Real Estate & Property,"If photos posted portal load, fit purpose. I'm...",Positive,0.225000,0.447222
64226,Housing-Real Estate & Property,"Dumb app, I wanted post property rent give opt...",Negative,-0.287500,0.250000
64227,Housing-Real Estate & Property,I property business got link SMS happy perform...,Positive,0.800000,1.000000
64230,Housing-Real Estate & Property,"Useless app, I searched flats kondapur, Hydera...",Negative,-0.316667,0.400000

#### Now, use the `value_counts()` function ([documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html)) to get a sense on how many apps are in this dataset and their review counts.

In [32]:
review_missing_removed.App.value_counts()

Bowmasters                                           312
Angry Birds Classic                                  273
Helix Jump                                           273
Calorie Counter - MyFitnessPal                       255
Candy Crush Saga                                     240
                                                    ...
Google Trips - Travel Planner                          1
Best Fiends - Free Puzzle Game                         1
Calendar+ Schedule Planner App                         1
HD Camera                                              1
CallApp: Caller ID, Blocker & Phone Call Recorder      1
Name: App, Length: 865, dtype: int64

In [33]:
review_missing_removed.App.value_counts().sum()

37432

#### Now the tough part comes. Let's plan how we will achieve our goal:

1. We will count the number of reviews that contain *Positive* in the `Sentiment` column.

1. We will create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app.

1. We will then loop the new dataframe to calculate the postivie review portion of each app.

#### Step 1: Count the number of positive reviews.

In the following cell, write a function that takes a column and returns the number of times *Positive* appears in the column. 

*Hint: One option is to use the `np.where()` function ([documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.where.html)).*

In [34]:
np.where(review_missing_removed['Sentiment'] == 'Positive', 1,0).sum()

23998

In [35]:
# Your code below

def positive_function(x):
    """
    Count how many times the string `Positive` appears in a column (exact string match).
    
    Args:
        x: data column
    
    Returns:
        The number of occurrences of `Positive` in the column data.
    """
    return np.where(x == 'Positive', 1,0).sum()

In [36]:
positive_function(review_missing_removed['Sentiment'])

23998

#### Step 2: Create a new dataframe to contain the `App` name, the number of positive reviews, and the total number of reviews of each app

We will group `review_missing_removed` by the `App` column, then aggregate the grouped dataframe on the number of positive reviews and the total review counts of each app. The result will be assigned to a new variable `google_agg`. Here is the ([documentation on how to achieve it](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.DataFrameGroupBy.agg.html)). Take a moment or two to read the documentation and google examples because it is pretty complex.

When you obtain `google_agg`, check its values to make sure it has an `App` column as its index as well as a `Positive` column and a `Total` column. Your output should look like:

![Positive Reviews Agg](../images/positive-review-agg.png)

*Hint: Use `positive_function` you created earlier as part of the param passed to the `agg()` function in order to aggregate the number of positive reviews.*

#### Bonus:

As of Pandas v0.23.4, you may opt to supply an array or an object to `agg()`. If you use the array param, you'll need to rename the columns so that their names are `Positive` and `Total`. Using the object param will allow you to create the aggregated columns with the desirable names without renaming them. However, you will probably encounter a warning indicating supplying an object to `agg()` will become outdated. It's up to you which way you will use. Try both ways out. Any way is fine as long as it works.

In [37]:
review_missing_removed.App

0                 10 Best Foods for You
1                 10 Best Foods for You
3                 10 Best Foods for You
4                 10 Best Foods for You
5                 10 Best Foods for You
                      ...
64222    Housing-Real Estate & Property
64223    Housing-Real Estate & Property
64226    Housing-Real Estate & Property
64227    Housing-Real Estate & Property
64230    Housing-Real Estate & Property
Name: App, Length: 37432, dtype: object

Print the first 5 rows of `google_agg` to check it.

In [38]:
# Your code here

#### Add a derived column to `google_agg` that is the ratio of the `Positive` and the `Total` columns. Call this column `Positive Ratio`. 

Make sure to account for the case where the denominator is zero using the `np.where()` function.

In [39]:
# Your code here:

#### Now drop the `Positive` and `Total` columns. Do this with `inplace=True`.

In [40]:
# Your code here:

Print the first 5 rows of `google_agg`. Your output should look like:

![Positive Reviews Agg](../images/positive-review-ratio.png)

In [41]:
# Your code here:

# Challenge 3 - Join the Dataframes

In this part of the lab, we will join the two dataframes and obtain a dataframe that contains features we can use in our ML algorithm.

In the next cell, join the `google_missing_removed` dataframe with the `google_agg` dataframe on the `App` column. Assign this dataframe to the variable `google`.

In [42]:
# Your code here:

#### Let's look at the final result using the `head()` function. Your final product should look like:

![Final Product](../images/google-final-head.png)

In [43]:
# Your code here: